"""Architecture-range adaptation: shape-group variant selection + anchor checks.

The Noto pole positions signs with anchors (GPOS marks, auto-generated by
Glyphs) and swaps sign SHAPES per base class instead of precomposing a glyph
per base:

    sub @uSignAlt2Group usign-sinh' by usign-sinh.alt2;

Which bases select which variant is designer knowledge, not derivable from
glyph presence — so the classes are harvested from the Glyphs source (or
injected) and rules are emitted only where a matching class exists. Where a
variant glyph exists but no class selects it, the validator reports it as an
actionable finding rather than guessing.
"""

from __future__ import annotations

from .generators import _alt_base_and_index
from .inventory import FontInventory
from .model import FeatureDoc, GlyphClass, Lookup, Rule
from .scripts import ScriptProfile

# Where a sign's variant-selection rule is registered (falls back to
# profile.sign_feature, then psts).
_VARIANT_FEATURE = {"rasign": "blws", "repha": "abvs", "yasign": "blws",
                    "virama": "abvs", "touch": "dist"}

# Class-name matching aliases (Noto vocabulary): rasign variants are selected
# by @rakar* classes, reph by @reph*, i/ii signs by @iVowel*, u/uu by @uSign*.
_STEM_ALIASES = {
    "rasign": ("rasign", "rakar"),
    "repha": ("repha", "reph"),
    "isign": ("isign", "ivowel"),
    "iisign": ("iisign", "iivowel", "ivowel"),
    "usign": ("usign", "uvowel"),
    "uusign": ("uusign", "uuvowel", "usign"),
}


def _sign_variants(inventory: FontInventory, namespace: str) -> list[tuple[str, str, int]]:
    """(sign_stem, variant_glyph, index) for every ``<sign>-<ns>.altN`` glyph."""
    suffix = f"-{namespace}"
    out = []
    for name in sorted(inventory.glyphs):
        parsed = _alt_base_and_index(name)
        if not parsed:
            continue
        base, idx = parsed
        if not base.endswith(suffix):
            continue
        stem = base[: -len(suffix)]
        if stem.endswith("sign") or stem in ("repha", "virama", "touch"):
            out.append((stem, name, idx))
    return out


def _matching_class(stem: str, idx: int, class_names) -> str | None:
    """Find a harvested class that selects this variant (e.g. uSignAlt2Group
    for usign.alt2, iVowelAlt2 for iisign.alt2, rephAltGroup for repha.alt1),
    by normalized substring match. An 'Alt' with no digit selects alt1."""
    import re

    keys = _STEM_ALIASES.get(stem, (stem,))
    for cname in class_names:
        low = cname.lower().replace("_", "")
        if f"alt{idx}" in low:
            pass
        elif idx == 1 and re.search(r"alt(?!\d)", low):
            pass
        else:
            continue
        if any(k in low for k in keys):
            return cname
    return None


def add_variant_selection(doc: FeatureDoc, profile: ScriptProfile,
                          inventory: FontInventory) -> list[str]:
    """Emit class-gated variant-selection rules; return findings for variants
    that exist but have no selecting class."""
    ns = profile.namespace
    findings: list[str] = []
    variants = _sign_variants(inventory, ns)
    if not variants:
        return findings

    # Make harvested classes available to the rules (dedup against existing).
    existing = {c.name for c in doc.classes}
    for cname, members in inventory.source_classes.items():
        if cname not in existing and members:
            doc.classes.append(GlyphClass(cname, list(members)))

    lookups: dict[str, Lookup] = {}
    for stem, variant, idx in variants:
        cname = _matching_class(stem, idx, inventory.source_classes.keys())
        if cname is None:
            findings.append(
                f"variant: {variant} present but no shape-group class selects "
                f"it — add a @…Alt{idx}… class in the source or via --inject")
            continue
        tag = _VARIANT_FEATURE.get(stem) or profile.sign_feature.get(stem, "psts")
        lk = lookups.setdefault(tag, Lookup(
            f"VariantSelection_{tag}", comment="shape-group sign variants"))
        sign = f"{stem}-{ns}"
        lk.rules.append(Rule(
            kind="single", inputs=[f"@{cname}", f"{sign}'"], output=variant,
            comment=f"{sign} -> {variant} after @{cname}",
        ))
    for tag, lk in lookups.items():
        doc.feature(tag).lookups.append(lk)
    return findings


# ---------------------------------------------------------------------------
# Anchor coverage validation (Glyphs sources only — binaries lack anchor data)
# ---------------------------------------------------------------------------

# Anchor families a Sinhala font uses for mark attachment (Noto vocabulary).
_MARK_ANCHOR_OF_SIGN = {
    "usign": "uvowel", "uusign": "uvowel",
    "isign": "iVowel", "iisign": "iiVowel",
    "virama": "alSign",
    "repha": "repaya",
    "rasign": "rakar",
}


def anchor_findings(inventory: FontInventory, satisfied_sign_counts: dict[str, int],
                    profile: ScriptProfile) -> list[str]:
    """For signs the font does NOT cover with precomposed ligatures, check the
    anchor pairing that GPOS mark attachment would need."""
    if not inventory.anchors:
        return []          # compiled font or anchor-less source: nothing to say
    ns = profile.namespace
    findings: list[str] = []
    consonant_bases = [f"{stem}a-{ns}" for stem in profile.tables.consonants.values()]

    for sign, base_anchor in _MARK_ANCHOR_OF_SIGN.items():
        sign_glyph = f"{sign}-{ns}"
        if sign_glyph not in inventory.glyphs:
            continue
        lig_count = satisfied_sign_counts.get(sign, 0)
        mark_anchors = inventory.anchors.get(sign_glyph, set())
        has_mark = any(a.startswith("_") for a in mark_anchors)
        carriers = [b for b in consonant_bases if b in inventory.glyphs]
        with_anchor = [b for b in carriers
                       if base_anchor in inventory.anchors.get(b, set())]
        if lig_count == 0 and not has_mark:
            findings.append(
                f"anchor: {sign_glyph} has no precomposed ligatures AND no "
                f"'_' mark anchor — it cannot attach; add '_{base_anchor}' to "
                f"the sign and '{base_anchor}' to bases, or draw ligatures")
        elif has_mark and carriers and len(with_anchor) < len(carriers):
            missing = len(carriers) - len(with_anchor)
            findings.append(
                f"anchor: {sign_glyph} attaches via '_{base_anchor}' but "
                f"{missing}/{len(carriers)} base consonants lack the "
                f"'{base_anchor}' anchor")
    return findings


def satisfied_sign_counts(checks, profile: ScriptProfile) -> dict[str, int]:
    """How many satisfiable rules consume each standalone sign as an input."""
    ns_suffix = f"-{profile.namespace}"
    counts: dict[str, int] = {}
    sign_names = set(profile.tables.sign_alone.values()) | {"repha", "rasign", "yasign"}
    for check in checks:
        if not check.satisfiable:
            continue
        for token in check.rule.inputs:
            t = token[:-1] if token.endswith("'") else token
            if t.startswith("@") or not t.endswith(ns_suffix):
                continue
            stem = t[: -len(ns_suffix)]
            if stem in sign_names:
                counts[stem] = counts.get(stem, 0) + 1
    return counts
