"""Serialize the IR to .fea text.

Two backends behind one interface:

* :class:`FeacomposerBackend` — uses ``tptq.feacomposer`` (the user's chosen typed
  eDSL) when it is importable.
* :class:`TextBackend` — a self-contained .fea emitter with the same output
  contract; the reliable fallback when feacomposer is absent or its pre-2.0 API has
  shifted.

Both accept a :class:`~lankafea.model.FeatureDoc` and return a .fea string. The
result is always re-validated by :func:`lankafea.verify.check_syntax` before use, so
a backend swap can never silently emit broken syntax.
"""

from __future__ import annotations

from .model import FeatureDoc, Feature, Lookup, Rule


def _fmt_seq(tokens: list[str]) -> str:
    return " ".join(tokens)


# Features that must not contain script/language statements.
_NO_SCRIPT_FEATURES = {"aalt", "size"}


class TextBackend:
    """Deterministic .fea text emitter (no third-party dependency)."""

    name = "text"

    def serialize(self, doc: FeatureDoc, language_systems: dict[str, list[str]]) -> str:
        lines: list[str] = []
        lines.append("# Generated by lankafea. Do not edit by hand.")
        lines.append("")
        for script, langs in language_systems.items():
            for lang in langs:
                lines.append(f"languagesystem {script} {lang};")
        lines.append("")

        # Named classes first (feaLib requires definition before use).
        for cls in doc.classes:
            if not cls.members:
                continue
            lines.append(f"@{cls.name} = [{_fmt_seq(cls.members)}];")
        if doc.classes:
            lines.append("")

        for feature in doc.features:
            block = self.emit_feature(feature)
            if block:
                lines.append(block)
                lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    def emit_feature(self, feature: Feature) -> str:
        if not any(lk.rules for lk in feature.lookups):
            return ""
        lines = [f"feature {feature.tag} {{"]
        # 'aalt' may not contain named lookup blocks — emit its rules inline.
        inline = feature.tag == "aalt"
        for lookup in feature.lookups:
            if not lookup.rules:
                continue
            if inline:
                for rule in lookup.rules:
                    lines.append(f"    {self._emit_rule(rule)}")
            else:
                lines.extend(self._emit_lookup(lookup, indent="    "))
        lines.append(f"}} {feature.tag};")
        return "\n".join(lines)

    def emit_feature_body(self, feature: Feature) -> str:
        """The inner feature code (no ``feature tag { ... } tag;`` wrapper).

        Used when writing into a Glyphs source, where GSFeature.code holds only the
        body and Glyphs supplies the wrapper.
        """
        block = self.emit_feature(feature)
        if not block:
            return ""
        inner = block.split("\n")[1:-1]  # drop first/last wrapper lines
        return "\n".join(line[4:] if line.startswith("    ") else line for line in inner)

    def _emit_lookup(self, lookup: Lookup, indent: str) -> list[str]:
        out: list[str] = []
        if lookup.comment:
            out.append(f"{indent}# {lookup.comment}")
        out.append(f"{indent}lookup {lookup.name} {{")
        inner = indent + "    "
        flags = list(lookup.flags)
        flag_line = ""
        if flags:
            flag_line = " ".join(flags)
        if lookup.mark_filter_set:
            mfs = f"UseMarkFilteringSet [{_fmt_seq(lookup.mark_filter_set)}]"
            flag_line = f"{flag_line} {mfs}".strip()
        if flag_line:
            out.append(f"{inner}lookupflag {flag_line};")
        for rule in lookup.rules:
            out.append(f"{inner}{self._emit_rule(rule)}")
        out.append(f"{indent}}} {lookup.name};")
        return out

    def _emit_rule(self, rule: Rule) -> str:
        c = f"  # {rule.comment}" if rule.comment else ""
        if rule.kind in ("ligature", "single"):
            return f"sub {_fmt_seq(rule.inputs)} by {rule.output};{c}"
        if rule.kind == "multiple":
            outs = rule.output if isinstance(rule.output, list) else [rule.output]
            return f"sub {rule.inputs[0]} by {_fmt_seq(outs)};{c}"
        if rule.kind == "alternate":
            return f"sub {rule.inputs[0]} from [{_fmt_seq(rule.output if isinstance(rule.output, list) else [rule.output])}];{c}"
        if rule.kind == "pos":
            return f"pos {rule.inputs[0]} {rule.value};{c}"
        raise ValueError(f"unknown rule kind: {rule.kind}")


class FeacomposerBackend:
    """Author rules through tptq.feacomposer when available.

    feacomposer is pre-2.0 and its surface may shift; we touch only the small,
    verified set of primitives (constructor, Lookup ctx-manager with ``feature=``,
    variadic ``sub``, ``glyphClass``, ``namedGlyphClass``, ``raw``, ``asFeatureFile``).
    Positioning and alternate rules — which the eDSL does not model directly — are
    emitted as raw .fea lines. On any failure the caller falls back to TextBackend.
    """

    name = "feacomposer"

    def __init__(self):
        from tptq.feacomposer import FeaComposer  # import-time availability check
        self._FeaComposer = FeaComposer

    def serialize(self, doc: FeatureDoc, language_systems: dict[str, list[str]]) -> str:
        systems = {s: set(langs) for s, langs in language_systems.items()}
        c = self._FeaComposer(languageSystems=systems)
        text = TextBackend()  # for raw pos/alternate lines
        for cls in doc.classes:
            if cls.members:
                c.namedGlyphClass(cls.name, list(cls.members))
        for feature in doc.features:
            if not any(lk.rules for lk in feature.lookups):
                continue
            # aalt / size may not carry script/language statements, which the
            # composer inserts automatically — emit those as raw feature blocks.
            if feature.tag in _NO_SCRIPT_FEATURES:
                c.raw(text.emit_feature(feature))
                continue
            for lookup in feature.lookups:
                if not lookup.rules:
                    continue
                self._emit_lookup(c, feature.tag, lookup, text)
        return str(c.asFeatureFile())

    def _emit_lookup(self, c, tag: str, lookup: Lookup, text: "TextBackend") -> None:
        flags: dict = {f: True for f in lookup.flags}
        if lookup.mark_filter_set:
            flags["UseMarkFilteringSet"] = c.glyphClass(list(lookup.mark_filter_set))
        with c.Lookup(lookup.name, feature=tag, flags=flags or None):
            for rule in lookup.rules:
                if rule.kind in ("ligature", "single"):
                    c.sub(*rule.inputs, by=rule.output)
                elif rule.kind == "multiple":
                    c.sub(rule.inputs[0], by=list(rule.output))
                else:  # pos / alternate -> raw .fea line
                    c.raw(text._emit_rule(rule))


def get_backend(prefer_feacomposer: bool = False):
    """Return a serializer backend.

    The built-in :class:`TextBackend` is the default and the validated path: it
    registers features under the correct script tag (e.g. ``sinh``) so the shaper
    applies them. The feacomposer backend is EXPERIMENTAL — with the pinned pre-2.0
    release it registers generated features under ``DFLT`` rather than the script
    tag, so its output may not shape. Opt in only to author through the eDSL.
    """
    if prefer_feacomposer:
        try:
            return FeacomposerBackend()
        except Exception:
            pass
    return TextBackend()
